package com.filebox.common.model;

import com.filebox.common.model.base.BaseAccountDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountDevice extends BaseAccountDevice<AccountDevice> {
	
}
