package com.filebox.common.model;

import com.filebox.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final int STATUS_DISABLE = 0 ;    //禁用，无法做任何事情
	public static final int STATUS_LOCK = 2;        //禁用，无法做任何事
	public static final int STATUS_OK = 1;          //正常、已激活
	public static final int IDENTITY_SUPER = 1;      //系统管理员
	public static final int IDENTITY_NORMAL = 2;        //普通管理员
	
	
	public boolean isStatusOk(){
		return getStatus() == STATUS_OK;
	}
	
	public boolean isStatusLock(){
		return getStatus() == STATUS_LOCK;
	}
	
	public boolean isStatusDisable(){
		return getStatus() == STATUS_DISABLE;
	} 
	
	public boolean isSuperAdmin(){
		return getRole() == IDENTITY_SUPER;
	}
	
	public boolean isNormalAdmin(){
		return getRole() == IDENTITY_NORMAL;
	}
	
	public Account removeSensitiveInfo() {
		remove("password", "salt");
		return this;
	}
}
