package com.filebox.common.model;

import com.filebox.common.model.base.BaseAdminLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLog extends BaseAdminLog<AdminLog> {
	
}
