package com.filebox.common.model;

import com.filebox.common.model.base.BaseAdvertising;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advertising extends BaseAdvertising<Advertising> {
	
}
