package com.filebox.common.model;

import com.filebox.common.model.base.BaseAdvertisingPhone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdvertisingPhone extends BaseAdvertisingPhone<AdvertisingPhone> {
	
}
