package com.filebox.common.model;

import com.filebox.common.model.base.BaseAdvType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdvType extends BaseAdvType<AdvType> {
	
}
