package com.filebox.common.model;

import com.filebox.common.model.base.BaseApiSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiSession extends BaseApiSession<ApiSession> {
	
}
