package com.filebox.common.model;

import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.Date;

import com.filebox.common.model.base.BaseBindApplication;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BindApplication extends BaseBindApplication<BindApplication> {
	public static final int BIND_CODE = 0;
	public static final int UNBIND_CODE = 1;
	public static final int REPAIR_CODE = 2;
	
	public static final int PENDING_STATUS = 0;
	public static final int PASS_STATUS = 1;
	
	public static int getApplicationCount(String deviceId) {
		int count = Db.find("select * from bind_application where device_id = ? and status = ?", deviceId, BindApplication.PENDING_STATUS).size();
		return count;
	}
	
	public static Date getCurrentTimeStamp() {
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance();
		String dateStr = dateFormat.format(date);
		System.out.println(dateStr);
		Date timeStamp = (Date)Timestamp.valueOf(dateStr);
		return timeStamp;
	}
	
//	public static int getUnbindApplicationCount(String deviceId) {
//		return Db.find("select * from bind_application where device_id = ? and code = ?", deviceId, BindApplication.UNBIND_CODE).size();
//	}
}
