package com.filebox.common.model;

import com.filebox.common.model.base.BaseBonusPoints;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BonusPoints extends BaseBonusPoints<BonusPoints> {
	public static final int OPEN_DOOR_POINT = 1;
	public static final int REPAIR_POINT = 2;
	public static final int OPEN_DOOR_REDUCE = -1;
	public static final int DAMAGE_REDUCE = -3;
	
}
