package com.filebox.common.model;

import com.filebox.common.model.base.BaseBoxOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BoxOrder extends BaseBoxOrder<BoxOrder> {
	
}
