package com.filebox.common.model;

import com.filebox.common.model.base.BaseCourierDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourierDevice extends BaseCourierDevice<CourierDevice> {
	
}
