package com.filebox.common.model;

import com.filebox.common.model.base.BaseFileCourier;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileCourier extends BaseFileCourier<FileCourier> {
	
}
