package com.filebox.common.model;

import com.filebox.common.model.base.BaseFileDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileDevice extends BaseFileDevice<FileDevice> {
	/**
	 * 未启用
	 */
	public static final int STATUS_DISABLE = 0;
	/**
	 * 启用
	 */
	public static final int STATUS_OK = 1;
	/**
	 * 
	 * 删除
	 */
	public static final int STATUS_DEL = 3;

	/**
	 * @return
	 */
	public boolean isDisable() {
		return getStatus() == STATUS_DISABLE;
	}

	public boolean isDelete() {
		return getStatus() == STATUS_DEL;
	}

}
