package com.filebox.common.model;

import com.filebox.common.model.base.BaseInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Information extends BaseInformation<Information> {
	
}
