package com.filebox.common.model;

import com.filebox.common.model.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	
}
