package com.filebox.common.model;

import com.filebox.common.model.base.BaseModelDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModelDetail extends BaseModelDetail<ModelDetail> {
	
}
