package com.filebox.common.model;

import com.filebox.common.model.base.BaseOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operator extends BaseOperator<Operator> {
	
}
