package com.filebox.common.model;

import com.filebox.common.model.base.BaseOwnerDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OwnerDetail extends BaseOwnerDetail<OwnerDetail> {
	
	private String phone ;
	public static final int STATUS_OK = 1;
	public static final int STATUS_LOCK = 0;
	
	public boolean isStatusOk(){
		return getOwnerDeviceStatus() == STATUS_OK;
	}
	
	public boolean isStatusLock(){
		return getOwnerDeviceStatus() == STATUS_LOCK;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	

				
}
