package com.filebox.common.model;

import com.filebox.common.model.base.BaseOwnerToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OwnerToken extends BaseOwnerToken<OwnerToken> {
	
}
