package com.filebox.common.model;

import com.filebox.common.model.base.BaseOwnerDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OwnerDevice extends BaseOwnerDevice<OwnerDevice> {
	
}
