package com.filebox.common.model;

import com.filebox.common.model.base.BasePadvertising;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Padvertising extends BasePadvertising<Padvertising> {
	
}
