package com.filebox.common.model;

import com.filebox.common.model.base.BasePickupRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PickupRecord extends BasePickupRecord<PickupRecord> {
	public static final int PICKUP_USER = 1;
	public static final int PICKUP_COURIER = 2;
	public static final int PICKUP_ADMIN = 3;
}
