package com.filebox.common.model;

import com.filebox.common.model.base.BasePostage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Postage extends BasePostage<Postage> {
	public static final int TYPE_SM = 1;
	public static final int TYPE_MD = 2;
	public static final int TYPE_LG = 3;
}
