package com.filebox.common.model;

import com.filebox.common.model.base.BaseProtocol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Protocol extends BaseProtocol<Protocol> {
	
}
