package com.filebox.common.model;

import com.filebox.common.model.base.BaseRechangeBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechangeBill extends BaseRechangeBill<RechangeBill> {
	
}
