package com.filebox.common.model;

import com.filebox.common.model.base.BaseSession;

/**
 * Generated by JFinal. Session 存在数据库中,并引入cache中间层，优点如下： 1:简单并且高性能 2：支持分布式和集群
 * 3：支持服务器断点和重启 4：支持tomcat、jetty等运行容器重启
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	private static final long serialVersionUID = 1L;
	public static final Session dao = new Session();

	/**
	 * 登录会话是否已过期
	 */
	public boolean isExpired() {
		return getExpireAt() < System.currentTimeMillis();
	}

	/**
	 * 登录会话是否未过期
	 */
	public boolean notExpired() {
		return !isExpired();
	}
}
