package com.filebox.common.model;

import com.filebox.common.model.base.BaseSpecialUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialUser extends BaseSpecialUser<SpecialUser> {
	public static final int STATUS_OK = 1;
	public static final int STATUS_LOCK = 0;
	
	public static final int TERMINAL_OK = 1;
	public static final int TERMINAL_NO = 0;
	
	public boolean isStatusOk(){
		return getStatus() == STATUS_OK;
	}
	
	public boolean isStatusLock(){
		return getStatus() == STATUS_LOCK;
	}
}
