package com.filebox.common.model;

import com.filebox.common.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public final static int STATUS_OK = 1;
}
