package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApiSession<M extends BaseApiSession<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
		return (M)this;
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public M setAccess(java.lang.Integer access) {
		set("access", access);
		return (M)this;
	}

	public java.lang.Integer getAccess() {
		return get("access");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
		return (M)this;
	}

	public java.lang.Long getExpireAt() {
		return get("expireAt");
	}

}
