package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFileCourier<M extends BaseFileCourier<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}

	public java.lang.Integer getOperatorId() {
		return get("operator_id");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setBalance(java.lang.Double balance) {
		set("balance", balance);
		return (M)this;
	}

	public java.lang.Double getBalance() {
		return get("balance");
	}

	public M setStorageNum(java.lang.Long storageNum) {
		set("storage_num", storageNum);
		return (M)this;
	}

	public java.lang.Long getStorageNum() {
		return get("storage_num");
	}

	public M setDeliveryNum(java.lang.Long deliveryNum) {
		set("delivery_num", deliveryNum);
		return (M)this;
	}

	public java.lang.Long getDeliveryNum() {
		return get("delivery_num");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setSysupdate(java.util.Date sysupdate) {
		set("sysupdate", sysupdate);
		return (M)this;
	}

	public java.util.Date getSysupdate() {
		return get("sysupdate");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

}
