package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBoxOrder<M extends BaseBoxOrder<M>> extends Model<M> implements IBean {

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public M setExpressId(java.lang.Integer expressId) {
		set("express_id", expressId);
		return (M)this;
	}

	public java.lang.Integer getExpressId() {
		return get("express_id");
	}

	public M setBoxNumber(java.lang.Integer boxNumber) {
		set("box_number", boxNumber);
		return (M)this;
	}

	public java.lang.Integer getBoxNumber() {
		return get("box_number");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCabinetNum(java.lang.Integer cabinetNum) {
		set("cabinet_num", cabinetNum);
		return (M)this;
	}

	public java.lang.Integer getCabinetNum() {
		return get("cabinet_num");
	}

}
