package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModelDetail<M extends BaseModelDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
		return (M)this;
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public M setBoxNum(java.lang.Integer boxNum) {
		set("box_num", boxNum);
		return (M)this;
	}

	public java.lang.Integer getBoxNum() {
		return get("box_num");
	}

	public M setBoxSpec(java.lang.Integer boxSpec) {
		set("box_spec", boxSpec);
		return (M)this;
	}

	public java.lang.Integer getBoxSpec() {
		return get("box_spec");
	}

	public M setBoxFloor(java.lang.Integer boxFloor) {
		set("box_floor", boxFloor);
		return (M)this;
	}

	public java.lang.Integer getBoxFloor() {
		return get("box_floor");
	}

}
