package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePickupRecord<M extends BasePickupRecord<M>> extends Model<M> implements IBean {

	public M setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
		return (M)this;
	}

	public java.lang.Integer getFileId() {
		return get("file_id");
	}

	public M setPickupPhone(java.lang.String pickupPhone) {
		set("pickup_phone", pickupPhone);
		return (M)this;
	}

	public java.lang.String getPickupPhone() {
		return get("pickup_phone");
	}

	public M setPickupTime(java.util.Date pickupTime) {
		set("pickup_time", pickupTime);
		return (M)this;
	}

	public java.util.Date getPickupTime() {
		return get("pickup_time");
	}

	public M setPickupIdentity(java.lang.Integer pickupIdentity) {
		set("pickup_identity", pickupIdentity);
		return (M)this;
	}

	public java.lang.Integer getPickupIdentity() {
		return get("pickup_identity");
	}

	public M setCost(java.math.BigDecimal cost) {
		set("cost", cost);
		return (M)this;
	}

	public java.math.BigDecimal getCost() {
		return get("cost");
	}

}
