package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechangeBill<M extends BaseRechangeBill<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}

	public java.lang.Integer getOperatorId() {
		return get("operator_id");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
		return (M)this;
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setPayPlatform(java.lang.Integer payPlatform) {
		set("pay_platform", payPlatform);
		return (M)this;
	}

	public java.lang.Integer getPayPlatform() {
		return get("pay_platform");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setAccountType(java.lang.Integer accountType) {
		set("account_type", accountType);
		return (M)this;
	}

	public java.lang.Integer getAccountType() {
		return get("account_type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setAmount(java.lang.Double amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Double getAmount() {
		return get("amount");
	}

}
