package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePostage<M extends BasePostage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setCost(java.lang.Double cost) {
		set("cost", cost);
		return (M)this;
	}

	public java.lang.Double getCost() {
		return get("cost");
	}

	public M setOverHourCost(java.lang.Double overHourCost) {
		set("over_hour_cost", overHourCost);
		return (M)this;
	}

	public java.lang.Double getOverHourCost() {
		return get("over_hour_cost");
	}

	public M setOverDayCost(java.lang.Double overDayCost) {
		set("over_day_cost", overDayCost);
		return (M)this;
	}

	public java.lang.Double getOverDayCost() {
		return get("over_day_cost");
	}

}
