package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFileBox<M extends BaseFileBox<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setCabinetNum(java.lang.Integer cabinetNum) {
		set("cabinet_num", cabinetNum);
		return (M)this;
	}

	public java.lang.Integer getCabinetNum() {
		return get("cabinet_num");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public M setSpec(java.lang.Integer spec) {
		set("spec", spec);
		return (M)this;
	}

	public java.lang.Integer getSpec() {
		return get("spec");
	}

	public M setCode(java.lang.Integer code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.Integer getCode() {
		return get("code");
	}

	public M setFloor(java.lang.Integer floor) {
		set("floor", floor);
		return (M)this;
	}

	public java.lang.Integer getFloor() {
		return get("floor");
	}

	public M setBoxStatus(java.lang.Integer boxStatus) {
		set("box_status", boxStatus);
		return (M)this;
	}

	public java.lang.Integer getBoxStatus() {
		return get("box_status");
	}

	public M setDoorStatus(java.lang.Integer doorStatus) {
		set("door_status", doorStatus);
		return (M)this;
	}

	public java.lang.Integer getDoorStatus() {
		return get("door_status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setSysupdate(java.util.Date sysupdate) {
		set("sysupdate", sysupdate);
		return (M)this;
	}

	public java.util.Date getSysupdate() {
		return get("sysupdate");
	}

}
