package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBindApplication<M extends BaseBindApplication<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setOwnerId(java.lang.Integer ownerId) {
		set("owner_id", ownerId);
		return (M)this;
	}

	public java.lang.Integer getOwnerId() {
		return get("owner_id");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setBoxId(java.lang.Integer boxId) {
		set("box_id", boxId);
		return (M)this;
	}

	public java.lang.Integer getBoxId() {
		return get("box_id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setCabinetNum(java.lang.Integer cabinetNum) {
		set("cabinet_num", cabinetNum);
		return (M)this;
	}

	public java.lang.Integer getCabinetNum() {
		return get("cabinet_num");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public M setCode(java.lang.Integer code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.Integer getCode() {
		return get("code");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setApplicationTime(java.util.Date applicationTime) {
		set("application_time", applicationTime);
		return (M)this;
	}

	public java.util.Date getApplicationTime() {
		return get("application_time");
	}

	public M setPassTime(java.util.Date passTime) {
		set("pass_time", passTime);
		return (M)this;
	}

	public java.util.Date getPassTime() {
		return get("pass_time");
	}

}
