package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdvertisingPhone<M extends BaseAdvertisingPhone<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setOperatorId(java.lang.Integer operatorId) {
		set("operatorId", operatorId);
		return (M)this;
	}

	public java.lang.Integer getOperatorId() {
		return get("operatorId");
	}

	public M setLink(java.lang.String link) {
		set("link", link);
		return (M)this;
	}

	public java.lang.String getLink() {
		return get("link");
	}

	public M setTextcontent(java.lang.String textcontent) {
		set("textcontent", textcontent);
		return (M)this;
	}

	public java.lang.String getTextcontent() {
		return get("textcontent");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}

	public java.lang.String getPhoto() {
		return get("photo");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public M setSysupdate(java.util.Date sysupdate) {
		set("sysupdate", sysupdate);
		return (M)this;
	}

	public java.util.Date getSysupdate() {
		return get("sysupdate");
	}

	public M setAdvStatus(java.lang.Integer advStatus) {
		set("adv_status", advStatus);
		return (M)this;
	}

	public java.lang.Integer getAdvStatus() {
		return get("adv_status");
	}

	public M setInformationlink(java.lang.String informationlink) {
		set("informationlink", informationlink);
		return (M)this;
	}

	public java.lang.String getInformationlink() {
		return get("informationlink");
	}

	public M setAdvTypeid(java.lang.Integer advTypeid) {
		set("adv_typeId", advTypeid);
		return (M)this;
	}

	public java.lang.Integer getAdvTypeid() {
		return get("adv_typeId");
	}

}
