package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
		return (M)this;
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public M setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
		return (M)this;
	}

	public java.lang.Long getExpireAt() {
		return get("expireAt");
	}

}
