package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccountDevice<M extends BaseAccountDevice<M>> extends Model<M> implements IBean {

	public M setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
		return (M)this;
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
