package com.filebox.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setCabinetNum(java.lang.Integer cabinetNum) {
		set("cabinet_num", cabinetNum);
		return (M)this;
	}

	public java.lang.Integer getCabinetNum() {
		return get("cabinet_num");
	}

	public M setBoxNumber(java.lang.Integer boxNumber) {
		set("box_number", boxNumber);
		return (M)this;
	}

	public java.lang.Integer getBoxNumber() {
		return get("box_number");
	}

	public M setCourierId(java.lang.Integer courierId) {
		set("courier_id", courierId);
		return (M)this;
	}

	public java.lang.Integer getCourierId() {
		return get("courier_id");
	}

	public M setTrackingNumber(java.lang.String trackingNumber) {
		set("tracking_number", trackingNumber);
		return (M)this;
	}

	public java.lang.String getTrackingNumber() {
		return get("tracking_number");
	}

	public M setReceivePhone(java.lang.String receivePhone) {
		set("receive_phone", receivePhone);
		return (M)this;
	}

	public java.lang.String getReceivePhone() {
		return get("receive_phone");
	}

	public M setCourierPhone(java.lang.String courierPhone) {
		set("courier_phone", courierPhone);
		return (M)this;
	}

	public java.lang.String getCourierPhone() {
		return get("courier_phone");
	}

	public M setSaveTime(java.util.Date saveTime) {
		set("save_time", saveTime);
		return (M)this;
	}

	public java.util.Date getSaveTime() {
		return get("save_time");
	}

	public M setBoxSpec(java.lang.Integer boxSpec) {
		set("box_spec", boxSpec);
		return (M)this;
	}

	public java.lang.Integer getBoxSpec() {
		return get("box_spec");
	}

	public M setOverTime(java.lang.Integer overTime) {
		set("over_time", overTime);
		return (M)this;
	}

	public java.lang.Integer getOverTime() {
		return get("over_time");
	}

	public M setNoticeTime(java.util.Date noticeTime) {
		set("notice_time", noticeTime);
		return (M)this;
	}

	public java.util.Date getNoticeTime() {
		return get("notice_time");
	}

	public M setSysupdate(java.util.Date sysupdate) {
		set("sysupdate", sysupdate);
		return (M)this;
	}

	public java.util.Date getSysupdate() {
		return get("sysupdate");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setPickupCode(java.lang.String pickupCode) {
		set("pickup_code", pickupCode);
		return (M)this;
	}

	public java.lang.String getPickupCode() {
		return get("pickup_code");
	}

	public M setOwnerId(java.lang.Integer ownerId) {
		set("owner_id", ownerId);
		return (M)this;
	}

	public java.lang.Integer getOwnerId() {
		return get("owner_id");
	}

}
